language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rathakur1992/docker-react -f Dockerfile.dev .  

script:
  - docker run -e CI=true rathakur1992/docker-react npm run test -- --coverage