language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rathakur1992/docker-react -f Dockerfile.dev .  

script:
  - docker run -e CI=true rathakur1992/docker-react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-ap-south-1-814938632402"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
